version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: eduSkillbridge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - skillbridge_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@skillbridge.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - skillbridge_net

  backend:
    build: ./backend
    restart: always
    environment:
      - PORT=5002
      - DATABASE_URL=postgres://postgres:your_db_password@db:5432/eduSkillbridge
      - FRONTEND_URL=https://eduskillbridge.net
      - JWT_SECRET=SkillBr1dge-!Secure.JWT-Key!
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=465
      - SMTP_SECURE=true
      - SMTP_USER=your@gmail.com
      - SMTP_PASS=your_app_password
    expose:
      - "5002"
    depends_on:
      - db
    networks:
      - skillbridge_net

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=https://eduskillbridge.net/api
    depends_on:
      - backend
    networks:
      - skillbridge_net

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
    networks:
      - skillbridge_net

volumes:
  postgres_data:
  pgadmin_data:

networks:
  skillbridge_net:
    driver: bridge
