services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://postgres:your_db_password@db:5432/skillbridge_db
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: skillbridge_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@skillbridge.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"  # ✅ Fixed port for pgAdmin
    depends_on:
      - db

volumes:
  postgres_data:
