version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eduSkillbridge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@skillbridge.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  backend:
    build: ./backend
    restart: always
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - DATABASE_URL=postgres://postgres:postgres@db:5432/eduSkillbridge
      - JWT_SECRET=SkillBr1dge-!Secure.JWT-Key!
      - FRONTEND_URL=https://eduskillbridge.net
    depends_on:
      - db
    volumes:
      - ./backend/src:/app/src  # ✅ This makes migrations show up locally

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:5002/api
    depends_on:
      - backend

volumes:
  postgres_data:
  pgadmin_data:
