env APP_DOMAIN;
events {}

http {
    map $APP_DOMAIN $app_domain {
        "" "";
        default $APP_DOMAIN;
    }

    map $app_domain $allowed_origin {
        "" "";
        default https://$app_domain;
    }

    # Load virtual hosts from the conf.d directory
    include conf.d/default.conf;
    include conf.d/ssl.conf;
}
