env APP_DOMAIN;
events {}

http {
    client_max_body_size 0;
    map $APP_DOMAIN $app_domain {
        "" _;
        default $APP_DOMAIN;
    }

    # Load virtual hosts from the conf.d directory
    include /etc/nginx/conf.d/*.conf;
}
