env APP_DOMAIN;
env ALLOWED_ORIGINS;  # Comma-separated list of allowed origins
events {}

http {
    map $APP_DOMAIN $app_domain {
        "" _;
        default $APP_DOMAIN;
    }

    map $ALLOWED_ORIGINS $allowed_origins {
        "" "";
        default $ALLOWED_ORIGINS;
    }

    map $allowed_origins $allowed_origins_list {
        "" "";
        default ",$allowed_origins,";
    }

    # Load virtual hosts from the conf.d directory
    include /etc/nginx/conf.d/*.conf;
}
