############################################
# HTTPS - Frontend (Next.js)
############################################
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name eduskillbridge.net www.eduskillbridge.net;

    client_max_body_size 100M;

    ssl_certificate /etc/letsencrypt/live/eduskillbridge.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/eduskillbridge.net/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    include /etc/nginx/snippets/common_locations.inc;
}

############################################
# HTTPS - Backend (Express API)
############################################
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name api.eduskillbridge.net whatsappapi.eduskillbridge.net;

    client_max_body_size 100M;

    ssl_certificate /etc/letsencrypt/live/eduskillbridge.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/eduskillbridge.net/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass http://backend:5002;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
