server {
    listen 443 ssl;
    server_name $app_domain www.$app_domain;
    # allow up to 100 MB uploads to avoid 413 errors
    client_max_body_size 100M;

    ssl_certificate /etc/letsencrypt/live/$app_domain/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$app_domain/privkey.pem;

    include /etc/nginx/conf.d/common_locations.conf;
}
