exports.seed = async function (knex) {
  const permissions = [
    { code: 'view_course', description: 'Permission to view courses' },
    { code: 'view_admin_dashboard', description: 'Permission to view admin dashboard' },
    { code: 'view_online_classes', description: 'Permission to view online classes' },
    { code: 'manage_online_classes', description: 'Permission to manage online classes' },
    { code: 'view_tutorials', description: 'Permission to view tutorials' },
    { code: 'manage_tutorials', description: 'Permission to manage tutorials' },
    { code: 'view_assignments', description: 'Permission to view assignments' },
    { code: 'manage_assignments', description: 'Permission to manage assignments' },
    { code: 'view_certificates', description: 'Permission to view certificates' },
    { code: 'manage_certificates', description: 'Permission to manage certificates' },
    { code: 'view_categories', description: 'Permission to view categories' },
    { code: 'manage_categories', description: 'Permission to manage categories' },
    { code: 'view_books', description: 'Permission to view books' },
    { code: 'manage_books', description: 'Permission to manage books' },
    { code: 'view_instructors', description: 'Permission to view instructors' },
    { code: 'manage_instructors', description: 'Permission to manage instructors' },
    { code: 'view_users', description: 'Permission to view users' },
    { code: 'manage_users', description: 'Permission to manage users' },
    { code: 'view_bookings', description: 'Permission to view bookings' },
    { code: 'manage_bookings', description: 'Permission to manage bookings' },
    { code: 'view_community', description: 'Permission to view community features' },
    { code: 'manage_community', description: 'Permission to manage community features' },
    { code: 'view_groups', description: 'Permission to view groups' },
    { code: 'manage_groups', description: 'Permission to manage groups' },
    { code: 'view_messages', description: 'Permission to view admin messages' },
    { code: 'manage_messages', description: 'Permission to manage admin messages' },
    { code: 'view_notifications', description: 'Permission to view notifications' },
    { code: 'manage_notifications', description: 'Permission to manage notifications' },
    { code: 'view_roles', description: 'Permission to view roles' },
    { code: 'manage_roles', description: 'Permission to manage roles' },
    { code: 'view_permissions', description: 'Permission to view permissions' },
    { code: 'manage_permissions', description: 'Permission to manage permissions' },
    { code: 'view_subscription_plans', description: 'Permission to view subscription plans' },
    { code: 'manage_subscription_plans', description: 'Permission to manage subscription plans' },
    { code: 'view_payment_config', description: 'Permission to view payment configuration' },
    { code: 'manage_payment_config', description: 'Permission to manage payment configuration' },
    { code: 'view_ads', description: 'Permission to view ads' },
    { code: 'manage_ads', description: 'Permission to manage ads' },
    { code: 'view_offers', description: 'Permission to view offers' },
    { code: 'manage_offers', description: 'Permission to manage offers' },
    { code: 'view_coupons', description: 'Permission to view coupons' },
    { code: 'manage_coupons', description: 'Permission to manage coupons' },
    { code: 'view_support', description: 'Permission to view support center' },
    { code: 'manage_support', description: 'Permission to manage support center' },
    { code: 'manage_cache', description: 'Permission to manage application cache' },
    { code: 'ADD_ONLINE_CLASS_RULE', description: 'Permission to manage class rules' },
    { code: 'view_languages', description: 'Permission to view languages' },
    { code: 'manage_languages', description: 'Permission to manage languages' },
    { code: 'view_language_config', description: 'Permission to view language configuration' },
    { code: 'manage_language_config', description: 'Permission to manage language configuration' },
    { code: 'view_currencies', description: 'Permission to view currencies' },
    { code: 'manage_currencies', description: 'Permission to manage currencies' },
    { code: 'view_social_logins', description: 'Permission to view social login settings' },
    { code: 'manage_social_logins', description: 'Permission to manage social login settings' },
    { code: 'view_email_config', description: 'Permission to view email configuration' },
    { code: 'manage_email_config', description: 'Permission to manage email configuration' },
    { code: 'view_messages_config', description: 'Permission to view messages configuration' },
    { code: 'manage_messages_config', description: 'Permission to manage messages configuration' },
    { code: 'view_policies', description: 'Permission to view policies' },
    { code: 'manage_policies', description: 'Permission to manage policies' },
    { code: 'view_contact_info', description: 'Permission to view contact information' },
    { code: 'manage_contact_info', description: 'Permission to manage contact information' },
    { code: 'view_blogs', description: 'Permission to view blogs' },
    { code: 'manage_blogs', description: 'Permission to manage blogs' },
    { code: 'view_faqs', description: 'Permission to view FAQs' },
    { code: 'manage_faqs', description: 'Permission to manage FAQs' },
    { code: 'view_app_settings', description: 'Permission to view application settings' },
    { code: 'manage_app_settings', description: 'Permission to manage application settings' },
    { code: 'view_footer_settings', description: 'Permission to view footer settings' },
    { code: 'manage_footer_settings', description: 'Permission to manage footer settings' },
    { code: 'view_seo_settings', description: 'Permission to view SEO settings' },
    { code: 'manage_seo_settings', description: 'Permission to manage SEO settings' },
    { code: 'view_popups', description: 'Permission to view popups and alerts' },
    { code: 'manage_popups', description: 'Permission to manage popups and alerts' },
    { code: 'view_certificate_templates', description: 'Permission to view certificate templates' },
    { code: 'manage_certificate_templates', description: 'Permission to manage certificate templates' },
    { code: 'view_third_party_config', description: 'Permission to view third-party configuration' },
    { code: 'manage_third_party_config', description: 'Permission to manage third-party configuration' },
  ];

  await knex('permissions')
    .insert(permissions)
    .onConflict('code')
    .ignore();
};
